on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: pip install streamlit openai
      - run: pwd
      - run: ls
      - run: cd ../
      - run: pwd
      - run: ls
